// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next'


const resData = [
	{
		"id": "BER",
		"createdAt": 1684146696,
		"updatedAt": 1684146696,
		"code": "BER",
		"name": "Hotel Berlin",
		"img": "http://localhost:3000/images/pics/hotel-1.jpg",
		"city": "Berlin",
		"countryCode": "DE",
		"description": "Explore the important places of recent history or simply enjoy the view over the rooftops of Berlin Mitte on our roof terrace.",
		"managingDirector": "",
		"defaultCheckinTime": "",
		"defaultCheckoutTime": "",
		"iban": "DE44 5001 0226 3375 2918 47",
		"bic": "SSKBDEBBXXY",
		"bank": "Stadtsparkasse Berlin",
		"timezone": "Europe/Berlin",
		"addressLine1": "Friedrichstraße 79-80900",
		"addressLine2": "dsad",
		"postalCode": "101172",
		"positionId": 1
	},
	{
		"id": "SUV0001",
		"createdAt": 1684146696,
		"updatedAt": 1684146696,
		"code": "SUV0001",
		"name": "Timesquare",
		"img": "http://localhost:3000/images/pics/hotel-2.jpg",
		"city": "Ho Chi Minh",
		"countryCode": "VN",
		"description": "",
		"managingDirector": "",
		"defaultCheckinTime": "",
		"defaultCheckoutTime": "",
		"iban": "",
		"bic": "",
		"bank": "",
		"timezone": "Asia/Saigon",
		"addressLine1": "Vietnam",
		"addressLine2": "Vietnam",
		"postalCode": "70000",
		"positionId": 2
	},
	{
		"id": "SWR",
		"createdAt": 1684208916,
		"updatedAt": 1684208916,
		"code": "SWR",
		"name": "Sonnenhotel Weingut Römmert",
		"img": "http://localhost:3000/images/pics/hotel-3.jpg",
		"city": "Volkach",
		"countryCode": "DE",
		"description": "string",
		"managingDirector": "Carsten Hinz",
		"defaultCheckinTime": "08:00",
		"defaultCheckoutTime": "19:00",
		"iban": "string",
		"bic": "string",
		"bank": "string",
		"timezone": "Europe/Berlin",
		"addressLine1": "Erlachhof 1a",
		"addressLine2": "",
		"postalCode": "97332",
		"positionId": 3
	},
	{
		"id": "SAH",
		"createdAt": 1684208991,
		"updatedAt": 1684208991,
		"code": "SAH",
		"name": "Sonnenhotel Amtsheide",
		"img": "http://localhost:3000/images/pics/hotel-4.jpg",
		"city": "Bad Bevensen",
		"countryCode": "DE",
		"description": "string",
		"managingDirector": "Kai Boie",
		"defaultCheckinTime": "08:00",
		"defaultCheckoutTime": "19:00",
		"iban": "string",
		"bic": "string",
		"bank": "string",
		"timezone": "Europe/Berlin",
		"addressLine1": "Zur Amtsheide 5 + 14",
		"addressLine2": "",
		"postalCode": "29549",
		"positionId": 4
	},
	{
		"id": "SEH",
		"createdAt": 1684209168,
		"updatedAt": 1684209168,
		"code": "SEH",
		"name": "Sonnenresort Ettershaus",
		"img": "http://localhost:3000/images/pics/hotel-5.jpg",
		"city": "Bad Harzburg",
		"countryCode": "DE",
		"description": "string",
		"managingDirector": "Frank Wyszkowski",
		"defaultCheckinTime": "08:00",
		"defaultCheckoutTime": "19:00",
		"iban": "string",
		"bic": "string",
		"bank": "string",
		"timezone": "Europe/Berlin",
		"addressLine1": "Nordhäuser Straße 1",
		"addressLine2": "",
		"postalCode": "38667",
		"positionId": 5
	},
	{
		"id": "SBH",
		"createdAt": 1684209313,
		"updatedAt": 1684209313,
		"code": "SBH",
		"name": "Sonnenhotel Bayerischer Hof",
		"img": "http://localhost:3000/images/pics/hotel-6.jpg",
		"city": "Waldmünchen",
		"countryCode": "DE",
		"description": "string",
		"managingDirector": "Steffen Kluge",
		"defaultCheckinTime": "08:00",
		"defaultCheckoutTime": "19:00",
		"iban": "string",
		"bic": "string",
		"bank": "string",
		"timezone": "Europe/Berlin",
		"addressLine1": "Torweiherweg 5",
		"addressLine2": "",
		"postalCode": "93449",
		"positionId": 6
	},
	{
		"id": "SFAS",
		"createdAt": 1684209348,
		"updatedAt": 1684209348,
		"code": "SFAS",
		"name": "Sonnenhotel Feldberg am See",
		"img": "http://localhost:3000/images/pics/hotel-7.jpg",
		"city": "Feldberg",
		"countryCode": "DE",
		"description": "string",
		"managingDirector": "Birgit Hasselbrinck",
		"defaultCheckinTime": "08:00",
		"defaultCheckoutTime": "19:00",
		"iban": "string",
		"bic": "string",
		"bank": "string",
		"timezone": "Europe/Berlin",
		"addressLine1": "Hinnenöver 18",
		"addressLine2": "",
		"postalCode": "17258",
		"positionId": 7
	},
	{
		"id": "SWH",
		"createdAt": 1684209467,
		"updatedAt": 1684209467,
		"code": "SWH",
		"name": "Sonnenhotel Wolfshof",
		"img": "http://localhost:3000/images/pics/hotel-8.jpg",
		"city": "Langelsheim",
		"countryCode": "DE",
		"description": "string",
		"managingDirector": "Harald Dörschel",
		"defaultCheckinTime": "08:00",
		"defaultCheckoutTime": "19:00",
		"iban": "string",
		"bic": "string",
		"bank": "string",
		"timezone": "Europe/Berlin",
		"addressLine1": "Kreuzallee 22-26",
		"addressLine2": "",
		"postalCode": "38685",
		"positionId": 8
	},
	{
		"id": "SHH",
		"createdAt": 1684209510,
		"updatedAt": 1684209510,
		"code": "SHH",
		"name": "Sonnenhotel Hoher Hahn",
		"img": "http://localhost:3000/images/pics/hotel-9.jpg",
		"city": "Schwarzenberg",
		"countryCode": "DE",
		"description": "string",
		"managingDirector": "Martin Wieggrebe",
		"defaultCheckinTime": "08:00",
		"defaultCheckoutTime": "19:00",
		"iban": "string",
		"bic": "string",
		"bank": "string",
		"timezone": "Europe/Berlin",
		"addressLine1": "Gemeindestraße 92",
		"addressLine2": "",
		"postalCode": "08340",
		"positionId": 9
	},
	{
		"id": "SFH",
		"createdAt": 1684209559,
		"updatedAt": 1684209559,
		"code": "SFH",
		"name": "Sonnenhotel Fürstenbauer",
		"img": "http://localhost:3000/images/pics/hotel-10.jpg",
		"city": "Bodenmais",
		"countryCode": "DE",
		"description": "string",
		"managingDirector": "",
		"defaultCheckinTime": "08:00",
		"defaultCheckoutTime": "19:00",
		"iban": "string",
		"bic": "string",
		"bank": "string",
		"timezone": "Europe/Berlin",
		"addressLine1": "Kötztinger Str. 34",
		"addressLine2": "",
		"postalCode": "94249",
		"positionId": 10
	},
	{
		"id": "SMS",
		"createdAt": 1684209608,
		"updatedAt": 1684209608,
		"code": "SMS",
		"name": "Sonnenresort Maltschacher See",
		"img": "http://localhost:3000/images/pics/hotel-11.jpg",
		"city": "Feldkirchen",
		"countryCode": "AT",
		"description": "string",
		"managingDirector": "Sylvia Della Pietra-Dorfer",
		"defaultCheckinTime": "08:00",
		"defaultCheckoutTime": "19:00",
		"iban": "string",
		"bic": "string",
		"bank": "string",
		"timezone": "Europe/Berlin",
		"addressLine1": "Maltschacher See Strasse 5",
		"addressLine2": "",
		"postalCode": "9560",
		"positionId": 11
	},
	{
		"id": "SOS",
		"createdAt": 1684209654,
		"updatedAt": 1684209654,
		"code": "SOS",
		"name": "Sonnenresort Ossiacher See",
		"img": "http://localhost:3000/images/pics/hotel-12.jpg",
		"city": "Ossiach",
		"countryCode": "AT",
		"description": "string",
		"managingDirector": "Astrid Spitzer-Scherling",
		"defaultCheckinTime": "08:00",
		"defaultCheckoutTime": "19:00",
		"iban": "string",
		"bic": "string",
		"bank": "string",
		"timezone": "Europe/Berlin",
		"addressLine1": "Alt-Ossiach 37",
		"addressLine2": "",
		"postalCode": "9570",
		"positionId": 12
	},
	{
		"id": "LND",
		"createdAt": 1684146696,
		"updatedAt": 1684146696,
		"code": "LND",
		"name": "Hotel London",
		"img": "http://localhost:3000/images/pics/hotel-13.jpg",
		"city": "London",
		"countryCode": "GB",
		"description": "Located in a quiet side street with a beautiful garden in the backyard, Hotel London is prefect for relaxing after a day of shopping or a night of partying.",
		"managingDirector": "",
		"defaultCheckinTime": "",
		"defaultCheckoutTime": "",
		"iban": "GB01 5001 0517 5407 3249 31",
		"bic": "SSKMDEMMXXX",
		"bank": "Bank of England",
		"timezone": "Europe/London",
		"addressLine1": "James Street 5",
		"addressLine2": "",
		"postalCode": "WC2E 8NS",
		"positionId":13
	},
	{
		"id": "PAR",
		"createdAt": 1684146696,
		"updatedAt": 1684146696,
		"code": "PAR",
		"name": "Hotel Paris",
		"img": "http://localhost:3000/images/pics/hotel-14.jpg",
		"city": "Paris",
		"countryCode": "FR",
		"description": "This new cozy hotel is located in the heart of Schwabing and is walking distance from the historical city center.",
		"managingDirector": "",
		"defaultCheckinTime": "",
		"defaultCheckoutTime": "",
		"iban": "FR44 5001 0517 5407 3249 31",
		"bic": "SSKMDEMMXXX",
		"bank": "Stadtsparkasse Paris",
		"timezone": "Europe/Paris",
		"addressLine1": "Leopoldstraße 8-10",
		"addressLine2": "",
		"postalCode": "80802",
		"positionId": 14
	},
	{
		"id": "VIE",
		"createdAt": 1684146696,
		"updatedAt": 1684146696,
		"code": "VIE",
		"name": "Hotel Vienna",
		"img": "http://localhost:3000/images/pics/hotel-15.jpg",
		"city": "Vienna",
		"countryCode": "AT",
		"description": "This new cozy hotel is located in the heart of Schwabing and is walking distance from the historical city center.",
		"managingDirector": "",
		"defaultCheckinTime": "",
		"defaultCheckoutTime": "",
		"iban": "AT61 1904 3002 3457 3201",
		"bic": "SSKBDEBBXYY",
		"bank": "Erste Bank",
		"timezone": "Europe/Vienna",
		"addressLine1": "Philharmoniker Str. 4",
		"addressLine2": "",
		"postalCode": "1010",
		"positionId": 15
	},
	{
		"id": "MUC",
		"createdAt": 1684146696,
		"updatedAt": 1684146696,
		"code": "MUC",
		"name": "Hotel Munich",
		"img": "http://localhost:3000/images/pics/hotel-16.jpg",
		"city": "Munich",
		"countryCode": "DE",
		"description": "This new cozy hotel is located in the heart of Schwabing and is walking distance from the historical city center.",
		"managingDirector": "",
		"defaultCheckinTime": "",
		"defaultCheckoutTime": "",
		"iban": "DE44 5001 0517 5407 3249 31",
		"bic": "SSKMDEMMXXX",
		"bank": "Stadtsparkasse München",
		"timezone": "Europe/Berlin",
		"addressLine1": "Leopoldstraße 8-10",
		"addressLine2": "ZMy",
		"postalCode": "80802",
		"positionId": 16
	}
]

export default function handler(req: NextApiRequest, res: NextApiResponse<any>) {
	const { page, perPage } = req.query;

	if (page && perPage) {
		const startPoint = Number(page) - 1;
		const endPoint = startPoint + Number(perPage);
		const totalCount = Math.ceil(resData.length);

		const dataSort = resData.sort((a:any, b:any) => {
			if(a.positionId < b.positionId) {
				return -1
			} else {
				return 1
			}
		})

		const data = dataSort.slice(startPoint, endPoint);


		res.status(200).json({ data, currentPage: Number(page), total: totalCount });
	} else {
		res.status(200).json( resData)
	}
	
}
