// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next'


const resData = {
    data: [
        {   
            "id": 1,
            "image": 'http://localhost:3000/images/pics/hotel-1.png',
            "favouriteHotel": true,
            "hotelName": 'Sonnenhotel Zum Stern',
            "description": 'Elegant and spacious living in the studio: 41 sqm, quietly located and mostly with a fantastic view of the large spa park or the pedestrian zone with shops and cafés. The high-quality furnishings with box-spring beds, air conditioning, capsule machine, flat-screen TV, minibar, safe, modern bathroom with rain shower or tub and rental bathrobe/slippers offer pure feel-good ambience. Some studios have a balcony.',
            "location": 'Weitmoserstrasse 33 5630 Bad Hofgastein, Austria',
            "tag": [
                {
                    "tagName": 'mountain air',
                    "tagId":'mountain-air',
                },
                {
                    "tagName": 'enjoyment',
                    "tagId":'enjoyment',
                },
                {
                    "tagName": 'wellness',
                    "tagId":'wellness',
                }
            ]
        },
        {   
            "id": 2,
            "image": 'http://localhost:3000/images/pics/hotel-2.png',
            "favouriteHotel": false,
            "hotelName": 'Sonnenresort Maltschacher See',
            "description": 'In the Hotel Maltschacher See, the holiday sun tickles your nose early in the morning and arouses anticipation of a perfect holiday day at the beautiful, warm Maltschacher See. The picture book backdrop of the Nockberge impresses young and old. Here in the spacious holiday village there are holiday ideas for the whole family. In the children\'s club, the dear Sonnenwolfi awaits the children with a fun program while the parents enjoy their time out and explore the area. The all-inclusive offer is practical. An all-round carefree package for unlimited holiday joy.',
            "location": 'Maltschacher See Strasse 5 9560 Feldkirchen, Austria',
            "tag": [
                {
                    "tagName": 'wein',
                    "tagId":'wein',
                },
                {
                    "tagName": 'inspiration',
                    "tagId":'inspiration',
                },
                {
                    "tagName": 'wellness',
                    "tagId":'wellness',
                }
            ]
        },
        {   
            "id": 3,
            "image": 'http://localhost:3000/images/pics/hotel-3.png',
            "favouriteHotel": false,
            "hotelName": 'Sonnenresort Ossiacher See',
            "description": 'The team at Sonnenresort Ossiacher See is already looking forward to welcoming you in 2024 with great innovations, such as renovations, extensions and a whole new spa area!',
            "location": 'Fleischmarkt 20, 1010 Wien, Austria',
            "tag": [
                {
                    "tagName": 'family',
                    "tagId":'family',
                },
                {
                    "tagName": 'sport',
                    "tagId":'sport',
                },
                {
                    "tagName": 'sport',
                    "tagId":'sport',
                }
            ]
        }
    ],
}


const hotelsData = {
	"code": 200,
	"data": [
	  {
		"data": [
		  {
			"id": "BER",
			"createdAt": 1684146696,
			"updatedAt": 1684146696,
			"code": "BER",
			"name": "Hotel Berlin",
            "image": 'http://localhost:3000/images/pics/hotel-1.png',
			"city": "Berlin",
			"countryCode": "DE",
			"description": "Explore the important places of recent history or simply enjoy the view over the rooftops of Berlin Mitte on our roof terrace.",
			"managingDirector": "",
			"defaultCheckinTime": "",
			"defaultCheckoutTime": "",
			"iban": "DE44 5001 0226 3375 2918 47",
			"bic": "SSKBDEBBXXY",
			"bank": "Stadtsparkasse Berlin",
			"timezone": "Europe/Berlin",
			"addressLine1": "Friedrichstraße 79-80900",
			"addressLine2": "dsad",
			"postalCode": "101172",
			"positionId": 1
		  },
		  {
			"id": "SUV0001",
			"createdAt": 1684146696,
			"updatedAt": 1684146696,
			"code": "SUV0001",
			"name": "Timesquare",
            "image": 'http://localhost:3000/images/pics/hotel-2.png',
			"city": "Ho Chi Minh",
			"countryCode": "VN",
			"description": "",
			"managingDirector": "",
			"defaultCheckinTime": "",
			"defaultCheckoutTime": "",
			"iban": "",
			"bic": "",
			"bank": "",
			"timezone": "Asia/Saigon",
			"addressLine1": "Vietnam",
			"addressLine2": "Vietnam",
			"postalCode": "70000",
			"positionId": 6
		  },
		  {
			"id": "SWR",
			"createdAt": 1684208916,
			"updatedAt": 1684208916,
			"code": "SWR",
			"name": "Sonnenhotel Weingut Römmert",
            "image": 'http://localhost:3000/images/pics/hotel-1.png',
			"city": "Volkach",
			"countryCode": "DE",
			"description": "string",
			"managingDirector": "Carsten Hinz",
			"defaultCheckinTime": "08:00",
			"defaultCheckoutTime": "19:00",
			"iban": "string",
			"bic": "string",
			"bank": "string",
			"timezone": "Europe/Berlin",
			"addressLine1": "Erlachhof 1a",
			"addressLine2": "",
			"postalCode": "97332",
			"positionId": 7
		  },
		  {
			"id": "SAH",
			"createdAt": 1684208991,
			"updatedAt": 1684208991,
			"code": "SAH",
			"name": "Sonnenhotel Amtsheide",
			"city": "Bad Bevensen",
			"countryCode": "DE",
			"description": "string",
			"managingDirector": "Kai Boie",
			"defaultCheckinTime": "08:00",
			"defaultCheckoutTime": "19:00",
			"iban": "string",
			"bic": "string",
			"bank": "string",
			"timezone": "Europe/Berlin",
			"addressLine1": "Zur Amtsheide 5 + 14",
			"addressLine2": "",
			"postalCode": "29549",
			"positionId": 8
		  },
		  {
			"id": "SEH",
			"createdAt": 1684209168,
			"updatedAt": 1684209168,
			"code": "SEH",
			"name": "Sonnenresort Ettershaus",
			"city": "Bad Harzburg",
			"countryCode": "DE",
			"description": "string",
			"managingDirector": "Frank Wyszkowski",
			"defaultCheckinTime": "08:00",
			"defaultCheckoutTime": "19:00",
			"iban": "string",
			"bic": "string",
			"bank": "string",
			"timezone": "Europe/Berlin",
			"addressLine1": "Nordhäuser Straße 1",
			"addressLine2": "",
			"postalCode": "38667",
			"positionId": 9
		  },
		  {
			"id": "SBH",
			"createdAt": 1684209313,
			"updatedAt": 1684209313,
			"code": "SBH",
			"name": "Sonnenhotel Bayerischer Hof",
			"city": "Waldmünchen",
			"countryCode": "DE",
			"description": "string",
			"managingDirector": "Steffen Kluge",
			"defaultCheckinTime": "08:00",
			"defaultCheckoutTime": "19:00",
			"iban": "string",
			"bic": "string",
			"bank": "string",
			"timezone": "Europe/Berlin",
			"addressLine1": "Torweiherweg 5",
			"addressLine2": "",
			"postalCode": "93449",
			"positionId": 10
		  },
		  {
			"id": "SFAS",
			"createdAt": 1684209348,
			"updatedAt": 1684209348,
			"code": "SFAS",
			"name": "Sonnenhotel Feldberg am See",
			"city": "Feldberg",
			"countryCode": "DE",
			"description": "string",
			"managingDirector": "Birgit Hasselbrinck",
			"defaultCheckinTime": "08:00",
			"defaultCheckoutTime": "19:00",
			"iban": "string",
			"bic": "string",
			"bank": "string",
			"timezone": "Europe/Berlin",
			"addressLine1": "Hinnenöver 18",
			"addressLine2": "",
			"postalCode": "17258",
			"positionId": 11
		  },
		  {
			"id": "SWH",
			"createdAt": 1684209467,
			"updatedAt": 1684209467,
			"code": "SWH",
			"name": "Sonnenhotel Wolfshof",
			"city": "Langelsheim",
			"countryCode": "DE",
			"description": "string",
			"managingDirector": "Harald Dörschel",
			"defaultCheckinTime": "08:00",
			"defaultCheckoutTime": "19:00",
			"iban": "string",
			"bic": "string",
			"bank": "string",
			"timezone": "Europe/Berlin",
			"addressLine1": "Kreuzallee 22-26",
			"addressLine2": "",
			"postalCode": "38685",
			"positionId": 12
		  },
		  {
			"id": "SHH",
			"createdAt": 1684209510,
			"updatedAt": 1684209510,
			"code": "SHH",
			"name": "Sonnenhotel Hoher Hahn",
			"city": "Schwarzenberg",
			"countryCode": "DE",
			"description": "string",
			"managingDirector": "Martin Wieggrebe",
			"defaultCheckinTime": "08:00",
			"defaultCheckoutTime": "19:00",
			"iban": "string",
			"bic": "string",
			"bank": "string",
			"timezone": "Europe/Berlin",
			"addressLine1": "Gemeindestraße 92",
			"addressLine2": "",
			"postalCode": "08340",
			"positionId": 13
		  },
		  {
			"id": "SFH",
			"createdAt": 1684209559,
			"updatedAt": 1684209559,
			"code": "SFH",
			"name": "Sonnenhotel Fürstenbauer",
			"city": "Bodenmais",
			"countryCode": "DE",
			"description": "string",
			"managingDirector": "",
			"defaultCheckinTime": "08:00",
			"defaultCheckoutTime": "19:00",
			"iban": "string",
			"bic": "string",
			"bank": "string",
			"timezone": "Europe/Berlin",
			"addressLine1": "Kötztinger Str. 34",
			"addressLine2": "",
			"postalCode": "94249",
			"positionId": 14
		  },
		  {
			"id": "SMS",
			"createdAt": 1684209608,
			"updatedAt": 1684209608,
			"code": "SMS",
			"name": "Sonnenresort Maltschacher See",
			"city": "Feldkirchen",
			"countryCode": "AT",
			"description": "string",
			"managingDirector": "Sylvia Della Pietra-Dorfer",
			"defaultCheckinTime": "08:00",
			"defaultCheckoutTime": "19:00",
			"iban": "string",
			"bic": "string",
			"bank": "string",
			"timezone": "Europe/Berlin",
			"addressLine1": "Maltschacher See Strasse 5",
			"addressLine2": "",
			"postalCode": "9560",
			"positionId": 15
		  },
		  {
			"id": "SOS",
			"createdAt": 1684209654,
			"updatedAt": 1684209654,
			"code": "SOS",
			"name": "Sonnenresort Ossiacher See",
			"city": "Ossiach",
			"countryCode": "AT",
			"description": "string",
			"managingDirector": "Astrid Spitzer-Scherling",
			"defaultCheckinTime": "08:00",
			"defaultCheckoutTime": "19:00",
			"iban": "string",
			"bic": "string",
			"bank": "string",
			"timezone": "Europe/Berlin",
			"addressLine1": "Alt-Ossiach 37",
			"addressLine2": "",
			"postalCode": "9570",
			"positionId": 16
		  },
		  {
			"id": "LND",
			"createdAt": 1684146696,
			"updatedAt": 1684146696,
			"code": "LND",
			"name": "Hotel London",
			"city": "London",
			"countryCode": "GB",
			"description": "Located in a quiet side street with a beautiful garden in the backyard, Hotel London is prefect for relaxing after a day of shopping or a night of partying.",
			"managingDirector": "",
			"defaultCheckinTime": "",
			"defaultCheckoutTime": "",
			"iban": "GB01 5001 0517 5407 3249 31",
			"bic": "SSKMDEMMXXX",
			"bank": "Bank of England",
			"timezone": "Europe/London",
			"addressLine1": "James Street 5",
			"addressLine2": "",
			"postalCode": "WC2E 8NS",
			"positionId": 3
		  },
		  {
			"id": "PAR",
			"createdAt": 1684146696,
			"updatedAt": 1684146696,
			"code": "PAR",
			"name": "Hotel Paris",
			"city": "Paris",
			"countryCode": "FR",
			"description": "This new cozy hotel is located in the heart of Schwabing and is walking distance from the historical city center.",
			"managingDirector": "",
			"defaultCheckinTime": "",
			"defaultCheckoutTime": "",
			"iban": "FR44 5001 0517 5407 3249 31",
			"bic": "SSKMDEMMXXX",
			"bank": "Stadtsparkasse Paris",
			"timezone": "Europe/Paris",
			"addressLine1": "Leopoldstraße 8-10",
			"addressLine2": "",
			"postalCode": "80802",
			"positionId": 4
		  },
		  {
			"id": "VIE",
			"createdAt": 1684146696,
			"updatedAt": 1684146696,
			"code": "VIE",
			"name": "Hotel Vienna",
			"city": "Vienna",
			"countryCode": "AT",
			"description": "This new cozy hotel is located in the heart of Schwabing and is walking distance from the historical city center.",
			"managingDirector": "",
			"defaultCheckinTime": "",
			"defaultCheckoutTime": "",
			"iban": "AT61 1904 3002 3457 3201",
			"bic": "SSKBDEBBXYY",
			"bank": "Erste Bank",
			"timezone": "Europe/Vienna",
			"addressLine1": "Philharmoniker Str. 4",
			"addressLine2": "",
			"postalCode": "1010",
			"positionId": 5
		  },
		  {
			"id": "MUC",
			"createdAt": 1684146696,
			"updatedAt": 1684146696,
			"code": "MUC",
			"name": "Hotel Munich",
			"city": "Munich",
			"countryCode": "DE",
			"description": "This new cozy hotel is located in the heart of Schwabing and is walking distance from the historical city center.",
			"managingDirector": "",
			"defaultCheckinTime": "",
			"defaultCheckoutTime": "",
			"iban": "DE44 5001 0517 5407 3249 31",
			"bic": "SSKMDEMMXXX",
			"bank": "Stadtsparkasse München",
			"timezone": "Europe/Berlin",
			"addressLine1": "Leopoldstraße 8-10",
			"addressLine2": "ZMy",
			"postalCode": "80802",
			"positionId": 2
		  }
		],
		"count": 16
	  }
	],
	"message": "success",
	"success": true
  }

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<any>
) {
  res.status(200).json(hotelsData);
}
